 fun getexptype (LT(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (LEQ(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (EQ(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (GT(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (GEQ(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (NEQ(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (AND(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (OR(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (PLUS(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (MINUS(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (TIMES(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (DIV(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (MOD(exp1,exp2)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (NEG(exp)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (NOT(exp)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (BOOLEAN(true)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (BOOLEAN(false)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (NUM(NUMBER)) = if getexptype(exp1) = getexptype(exp2) then 
    |getexptype (VAR(IDENTIFIER)) = if getexptype(exp1) = getexptype(exp2) then 